"""add admin_id column to group

Revision ID: 5724c8d01ce3
Revises: b866bf87e95e
Create Date: 2024-12-17 17:12:59.119560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5724c8d01ce3'
down_revision = 'b866bf87e95e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_group_admin', 'user', ['admin_id'], ['id'])

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_like', ['user_id', 'post_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint('unique_like', type_='unique')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
